#!/bin/bash
container_name=d7024e_container
for i in {0..500}
do
	if [[ $(docker ps -aq -f name=$container_name$i) != "" ]]
        then
		if [[ $(docker ps -aq -f status=exited -f name=$container_name$i) != "" ]]
                then
			echo "Removing container $container_name$i"
			docker rm $container_name$i $2>/dev/null
		else
			echo "Container $container_name$i is running; cant remove"
		fi
	fi
done
echo "All containers removed!"

docker rmi d7024e --force

echo "Image removed!"
