#!/bin/bash

container_name=d7024e_container
delay=1

#Build image
echo "Building docker image"
docker build -t d7024e .

if [[ $(docker ps -aq -f status=running -f name=$container_name'0') == "" ]]
then
	echo "Starting the first container"
	docker run -d --rm -p 8000:8000/udp -p 8000:8000 -e PORT=8000 --name $container_name'0' d7024e $2>/dev/null &
	echo "Sleeping for 3 seconds"
	sleep 3
fi

for i in {1..40}
do
	if [[ $(docker ps -aq -f status=running -f name=$container_name$i) == "" ]]
  then
		echo "Creating container $container_name$i"
		docker run -d --rm -p $((8000+$i)):$((8000+$i))/udp -p $((8000+$i)):$((8000+$i)) -e PORT=$((8000+$i)) --name $container_name$i d7024e $2>/dev/null &
		sleep $delay
	fi

done
echo "All containers started!"
