#!/bin/bash
container_name=d7024e_container
for i in {0..500}
do
	if [[ $(docker ps -aq -f status=running -f name=$container_name$i) != "" ]]
  then
		echo "Stopping container $container_name$i"
		docker stop $container_name$i $2>/dev/null &
	fi
done
echo "All containers stopped!"
